### ISSUE TITLE
Backend minimal functionality tracker

### ISSUE THREAD

**Issue by tudurom** [StudieverenigingSTORM/knt#12]
API:

- [x] Products
      Create, read, update, delete products.
- [x] Orders
      Place orders. Users need to be authenticated to place an order, which also
      takes money from their account (obviously). Orders should be anonymised (don't store which user bought what)?
        - Conscribo API might be useful here
- [x] Users
  - [x] Schema and basic API #6
  - [x] Creating, updating and deleting only possible by admins / webshop (for moneys).
      Reading (unauthenticated) only for listing them.
- [x] #15
  - [x] For users, to buy stuff.
        Once authenticated, a user may see all their details.
  - [x] For the webshop, to put money.
  - [x] For admins, to have full access.
- [x] #19

-------

I will later add issues / PRs next to the items of concern.

**Comment by TadMaj** [comment]
The one thing we have left for basic functionality is the ability to keep track of tax categories.

**Comment by TadMaj** [comment]
Done
