### ISSUE TITLE
Front-end tracker

### ISSUE THREAD

**Issue by EStroiu** [StudieverenigingSTORM/knt#27]
To do list for now:
- [x] Basic layout wireframe 
- [x] Barebones implementation of UserIndex page
- [x] Communication with backend for UserIndex page
- [ ] Barebone implementation of Product page
- [ ] Communication with backend for Product page
- [x] Router between the pages

- [x] API key hiding (SSR)

**Comment by EStroiu** [comment]
Current layout design, will edit when/if changes 
![front-wireframe](https://user-images.githubusercontent.com/80272300/231896241-20fd5d5d-0a28-4a84-b66c-080173192ade.png)
